### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by nikita-moor** [Arithmeticus/TAN-class-3#1]
Your collection contains lexicons of the Greek and Latin languages. Could I know the source of this data? It seems to be from Perseus, but where are the original files located?

**Comment by Arithmeticus** [comment]
Each of the files points via &lt;vocabulary> or &lt;vocabulary-key> to the point of origin. Your question is good though. The Greek and Latin Perseus originals I used, dated 2011, were provided to me on a non-public link, because each database was > 1GB. If the source or its successor ever gets exposed in full, I'll definitely incorporate that information into the vocabulary.

**Comment by nikita-moor** [comment]
Thank you.
